

module.exports = [
  {
    firstName: 'Alberta',
    lastName: 'Zitting',
    email: '',
    phone: 4356914716,
    affiliation: 7,
    gender: 'female',
  },
  {
    firstName: 'Alice',
    lastName: 'Timpson',
    email: 'alicehammon@gmail.com',
    phone: '435-212-0318',
    affiliation: 7,
    gender: 'female',
  },
  {
    firstName: 'Alina',
    lastName: 'Timpson',
    email: 'alinatimpson@hotmail.com',
    phone: '435-212-0206',
    affiliation: 3,
    gender: 'female',
  },
  {
    firstName: 'Alyne',
    lastName: 'Timpson',
    email: 'alynejt@hotmail.com',
    phone: '928-875-2111',
    affiliation: '8 Head',
    gender: 'female',
  },
  {
    firstName: 'Amanda K.',
    lastName: 'Timpson',
    email: 'amandaknudson1@hotmail.com',
    phone: '435-212-3049',
    affiliation: 2,
    gender: 'female',
  },
  {
    firstName: 'Amanda M.',
    lastName: 'Timpson',
    email: 'amandam@masadaschool.com',
    phone: '435-212-0791',
    affiliation: 3,
    gender: 'female',
  },
  {
    firstName: 'Amelia',
    lastName: 'Zitting',
    email: 'zittingamelia@gmail.com',
    phone: 4356914410,
    affiliation: 7,
    gender: 'female',
  },
  {
    firstName: 'Amelia K.',
    lastName: 'Timpson',
    email: 'amelia.knudson@gmail.com',
    phone: '435-212-3452',
    affiliation: 10,
    gender: 'female',
  },
  {
    firstName: 'Anne',
    lastName: 'Hammon',
    email: 'anne.hammon@elcap.us',
    phone: 4356910355,
    affiliation: 2,
    gender: 'female',
  },
  {
    firstName: 'Anne',
    lastName: 'Dockstader',
    email: 'annedockstader@yahoo.com',
    phone: '435-467-8110',
    affiliation: 6,
    gender: 'female',
  },
  {
    firstName: 'Anne',
    lastName: 'Timpson',
    email: 'annedock86@hotmail.com',
    phone: '435-212-0813',
    affiliation: 5,
    gender: 'female',
  },
  {
    firstName: 'Athena',
    lastName: 'Dockstader',
    email: 'NA',
    phone: '928-875-2128',
    affiliation: 3,
    gender: 'female',
  },
  {
    firstName: 'Beth',
    lastName: 'Knudson',
    email: 'bethmhammon@hotmail.com',
    phone: '435-616-2356',
    affiliation: 7,
    gender: 'female',
  },
  {
    firstName: 'Carol',
    lastName: 'Hammon',
    email: 'carolehammon@hotmail.com',
    phone: '435-691-4379',
    affiliation: 6,
    gender: 'female',
  },
  {
    firstName: 'Cassandra',
    lastName: 'Knudson',
    email: 'cassandrac@masadaschool.com',
    phone: '435-212-3307',
    affiliation: 6,
    gender: 'female',
  },
  {
    firstName: 'Charity',
    lastName: 'Dutson',
    email: 'charwill75@hotmail.com',
    phone: '928-875-8098',
    affiliation: 5,
    gender: 'female',
  },
  {
    firstName: 'Chelsea',
    lastName: 'Berg',
    email: 'ctimpson44@hotmail.com',
    phone: 4352120159,
    affiliation: 4,
    gender: 'female',
  },
  {
    firstName: 'Connie',
    lastName: 'Cawley',
    email: 'crwcawley@yahoo.com',
    phone: 4352120549,
    affiliation: 6,
    gender: 'female',
  },
  {
    firstName: 'Daisy Z',
    lastName: 'Timpson',
    email: 'zittingdazy@gmail.com',
    phone: 4354672239,
    affiliation: 8,
    gender: 'female',
  },
  {
    firstName: 'Danielle',
    lastName: 'Dockstader',
    email: 'danielledockstader@gmail.com',
    phone: '435-212-0038',
    affiliation: 7,
    gender: 'female',
  },
  {
    firstName: 'Dianne',
    lastName: 'Timpson',
    email: 'diannet@masadaschool.com',
    phone: '435-212-0666',
    affiliation: '2 Head',
    gender: 'female',
  },
  {
    firstName: 'Elaine B.',
    lastName: 'Timpson',
    email: 'elainebt76@hotmail.com',
    phone: '435-212-0156',
    affiliation: 2,
    gender: 'female',
  },
  {
    firstName: 'Elaine R.',
    lastName: 'Timpson',
    email: 'elaineroundy@hotmail.com',
    phone: '435-616-5353',
    affiliation: 9,
    gender: 'female',
  },
  {
    firstName: 'Elda Mae',
    lastName: 'Timpson',
    email: 'emt@elcap.us',
    phone: '435-212-0848',
    affiliation: 7,
    gender: 'female',
  },
  {
    firstName: 'Elizabeth',
    lastName: 'Kelsch',
    email: 'elizabeth.kelsch97@gmail.com',
    phone: '435-212-0332',
    affiliation: 6,
    gender: 'female',
  },
  {
    firstName: 'Elizabeth',
    lastName: 'Hammon',
    email: 'elizabeth@elcap.us',
    phone: '435-668-7553',
    affiliation: 5,
    gender: 'female',
  },
  {
    firstName: 'Elizabeth',
    lastName: 'Knudson',
    email: 'liz@cpaz.net',
    phone: '435-212-3327',
    affiliation: 8,
    gender: 'female',
  },
  {
    firstName: 'Ellen T',
    lastName: 'Zitting',
    email: 'ellentimpson_m14@hotmail.com',
    phone: 4352128020,
    affiliation: '',
    gender: 'female',
  },
  {
    firstName: 'Ellie',
    lastName: 'Timpson',
    email: 'ellie@cpaz.net',
    phone: 4354678010,
    affiliation: '6 Head',
    gender: 'female',
  },
  {
    firstName: 'Erin',
    lastName: 'Timpson',
    email: 'erink58@hotmail.com',
    phone: '435-616-3746',
    affiliation: '5 Head',
    gender: 'female',
  },
  {
    firstName: 'Esther',
    lastName: 'Hammon',
    email: 'estherh@masadaschool.com',
    phone: '435-616-8582',
    affiliation: 3,
    gender: 'female',
  },
  {
    firstName: 'Evie',
    lastName: 'Timpson',
    email: 'klazykritta@hotmail.com',
    phone: '435-668-6390',
    affiliation: 10,
    gender: 'female',
  },
  {
    firstName: 'Fawn',
    lastName: 'Bradshaw',
    email: 'fabulousfawnetta@hotmail.com',
    phone: '435-467-2043',
    affiliation: 1,
    gender: 'female',
  },
  {
    firstName: 'Francis',
    lastName: 'Cawley',
    email: 'fkcawley2@live.com',
    phone: '435-212-0424',
    affiliation: 8,
    gender: 'female',
  },
  {
    firstName: 'Guinevere',
    lastName: 'Dutson',
    email: 'gtdutson@hotmail.com',
    phone: '435-467-9039',
    affiliation: '4 Head',
    gender: 'female',
  },
  {
    firstName: 'Hazel',
    lastName: 'Zitting',
    email: 'hazyzitting@gmail.com',
    phone: '435-467-2240',
    affiliation: 7,
    gender: 'female',
  },
  {
    firstName: 'Helen',
    lastName: 'Hammon',
    email: 'helenhammon@hotmail.com',
    phone: '435-212-3023',
    affiliation: '3 Head',
    gender: 'female',
  },
  {
    firstName: 'Holly',
    lastName: 'Timpson',
    email: 'coffeegirlz@hotmail.com',
    phone: '801-503-1091',
    affiliation: 8,
    gender: 'female',
  },
  {
    firstName: 'Irma',
    lastName: 'Cook',
    email: 'noelfrieda@cpaz.net',
    phone: '435-212-8051',
    affiliation: 6,
    gender: 'female',
  },
  {
    firstName: 'Janet',
    lastName: 'Timpson',
    email: 'janettimpson1269@gmail.com',
    phone: '435-212-0696',
    affiliation: 7,
    gender: 'female',
  },
  {
    firstName: 'Janette',
    lastName: 'Barlow',
    email: 'nett.75@hotmail.com',
    phone: '435-691-2118',
    affiliation: 4,
    gender: 'female',
  },
  {
    firstName: 'Jeanetta',
    lastName: 'Hammon',
    email: 'jeanettah@masadaschool.com',
    phone: '435-616-8152',
    affiliation: '9 Head',
    gender: 'female',
  },
  {
    firstName: 'Jeanna',
    lastName: 'Timpson',
    email: 'jeanna_zitting@hotmail.com',
    phone: '435-467-0446',
    affiliation: 8,
    gender: 'female',
  },
  {
    firstName: 'Jennifer',
    lastName: 'Hammon',
    email: 'jennhammon@hotmail.com',
    phone: '435-212-3497',
    affiliation: 2,
    gender: 'female',
  },
  {
    firstName: 'Judy B.',
    lastName: 'Zitting',
    email: 'judbrad71@yahoo.com',
    phone: '435-467-5839',
    affiliation: 3,
    gender: 'female',
  },
  {
    firstName: 'Julena',
    lastName: 'Timpson',
    email: 'julena@cpaz.net',
    phone: '435-691-5853',
    affiliation: 1,
    gender: 'female',
  },
  {
    firstName: 'Kathleen',
    lastName: 'Timpson',
    email: 'ktimpson_1@hotmail.com',
    phone: 4352383213,
    affiliation: 6,
    gender: 'female',
  },
  {
    firstName: 'Kathryn',
    lastName: 'Knudson',
    email: 'kateknudson@gmail.com',
    phone: '435-616-2738',
    affiliation: 4,
    gender: 'female',
  },
  {
    firstName: 'Kaylene',
    lastName: 'Cawley',
    email: 'kellicious_c@hotmail.com',
    phone: '702-524-1336',
    affiliation: 8,
    gender: 'female',
  },
  {
    firstName: 'Kellie',
    lastName: 'Timpson',
    email: 'kellz_blondy@hotmail.com',
    phone: '435-691-3229',
    affiliation: 7,
    gender: 'female',
  },
  {
    firstName: 'Kiersten',
    lastName: 'Timpson',
    email: 'krstnmarie94@gmail.com',
    phone: '435-251-7420',
    affiliation: 1,
    gender: 'female',
  },
  {
    firstName: 'Kimberly',
    lastName: 'Barlow',
    email: 'meewee_76@hotmail.com',
    phone: '435-680-2800',
    affiliation: 4,
    gender: 'female',
  },
  {
    firstName: 'Kristin',
    lastName: 'Hammon',
    email: 'Kristin_zitting2005@hotmail.com',
    phone: '435-212-0571',
    affiliation: 1,
    gender: 'female',
  },
  {
    firstName: 'Leah D.',
    lastName: 'Hammon',
    email: 'gummies20091@hotmail.com',
    phone: '435-212-0722',
    affiliation: 10,
    gender: 'female',
  },
  {
    firstName: 'Leah J.',
    lastName: 'Hammon',
    email: 'leahh@masadaschool.com',
    phone: '435-212-0572',
    affiliation: 1,
    gender: 'female',
  },
  {
    firstName: 'LeAnne',
    lastName: 'Timpson',
    email: 'leannet@masadaschool.com',
    phone: '435-467-2673',
    affiliation: 3,
    gender: 'female',
  },
  {
    firstName: 'Linda',
    lastName: 'Chatwin',
    email: 'lmchatwin@yahoo.com',
    phone: '801-5505076',
    affiliation: 4,
    gender: 'female',
  },
  {
    firstName: 'Lisa',
    lastName: 'Hammon',
    email: 'hammonlisa@yahoo.com',
    phone: '435-691-5231',
    affiliation: 4,
    gender: 'female',
  },
  {
    firstName: 'Lois',
    lastName: 'Hammon',
    email: 'loishammon@yahoo.com',
    phone: '435-616-8582',
    affiliation: 1,
    gender: 'female',
  },
  {
    firstName: 'Lola',
    lastName: 'Zitting',
    email: 'lolaz30@hotmail.com',
    phone: '435-691-4313',
    affiliation: 6,
    gender: 'female',
  },
  {
    firstName: 'Louise',
    lastName: 'Dockstader',
    email: 'weez_t92@hotmail.com',
    phone: 4352120934,
    affiliation: 2,
    gender: 'female',
  },
  {
    firstName: 'Lucy',
    lastName: 'Zitting',
    email: 'lucy_26_91@hotmail.com',
    phone: '801-573-3435',
    affiliation: 10,
    gender: 'female',
  },
  {
    firstName: 'Mandy',
    lastName: 'Timpson',
    email: 'mandybandito@hotmail.com',
    phone: '435-212-0862',
    affiliation: 5,
    gender: 'female',
  },
  {
    firstName: 'Margaret K.',
    lastName: 'Timpson',
    email: 'margaret_knudson@hotmail.com',
    phone: '435-691-4286',
    affiliation: 4,
    gender: 'female',
  },
  {
    firstName: 'Margaret T.',
    lastName: 'Musser',
    email: 'margt73@hotmail.com',
    phone: '435-616-2145',
    affiliation: 3,
    gender: 'female',
  },
  {
    firstName: 'Marie',
    lastName: 'Musser',
    email: 'gmtimpson@hotmail.com',
    phone: '435-467-5289',
    affiliation: 9,
    gender: 'female',
  },
  {
    firstName: 'Marie',
    lastName: 'Holm',
    email: 'mholm77@gmail.com',
    phone: '435-212-0041',
    affiliation: 4,
    gender: 'female',
  },
  {
    firstName: 'Marie H.',
    lastName: 'Timpson',
    email: 'vtimpson@gmail.com',
    phone: '435-691-4807',
    affiliation: '1 head',
    gender: 'female',
  },
  {
    firstName: 'Marla',
    lastName: 'Zitting',
    email: 'marlaz@cpaz.net',
    phone: '435-467-3976',
    affiliation: 2,
    gender: 'female',
  },
  {
    firstName: 'Marleen',
    lastName: 'Barlow',
    email: 'marleen_barlow@hotmail.com',
    phone: '435-619-9627',
    affiliation: 3,
    gender: 'female',
  },
  {
    firstName: 'Martha',
    lastName: 'Hammon',
    email: 'martha_hammon@hotmail.com',
    phone: '435-467-8250',
    affiliation: 4,
    gender: 'female',
  },
  {
    firstName: 'Martha',
    lastName: 'LeBaron',
    email: 'marty_hammon@hotmail.com',
    phone: '435-212-3706',
    affiliation: 7,
    gender: 'female',
  },
  {
    firstName: 'Mary',
    lastName: 'Timpson',
    email: 'maryt@masadaschool.com',
    phone: '435-212-0369',
    affiliation: 7,
    gender: 'female',
  },
  {
    firstName: 'Mary Beth',
    lastName: 'Holm',
    email: 'marytim_730@hotmail.com',
    phone: '435-212-3151',
    affiliation: 9,
    gender: 'female',
  },
  {
    firstName: 'Melissa',
    lastName: 'Hammon',
    email: 'm_zitting86@hotmail.com',
    phone: 4356914835,
    affiliation: 4,
    gender: 'female',
  },
  {
    firstName: 'Michelle',
    lastName: 'Dockstader',
    email: 'michelle_dockstader@hotmail.com',
    phone: '435-705-1051',
    affiliation: 'Single',
    gender: 'female',
  },
  {
    firstName: 'Michelle',
    lastName: 'Timpson',
    email: 'Michelle@elcap.us',
    phone: '435-212-8222',
    affiliation: 2,
    gender: 'female',
  },
  {
    firstName: 'Michelle Wayman',
    lastName: 'Timpson',
    email: 'mayberry_2386@hotmail.com',
    phone: 4352120723,
    affiliation: 3,
    gender: 'female',
  },
  {
    firstName: 'Misti',
    lastName: 'Barlow',
    email: 'meewee_76@hotmail.com',
    phone: '435-691-4425',
    affiliation: 5,
    gender: 'female',
  },
  {
    firstName: 'Naomi',
    lastName: 'Dockstader',
    email: 'ntdnails@hotmail.com',
    phone: 4354673616,
    affiliation: 2,
    gender: 'female',
  },
  {
    firstName: 'Nellie',
    lastName: 'Timpson',
    email: 'nellietimpson@gmail.com',
    phone: '435-851-0167',
    affiliation: 5,
    gender: 'female',
  },
  {
    firstName: 'Priscilla',
    lastName: 'Hammon',
    email: 'priscillahammon@cpaz.net',
    phone: '435-467-3551',
    affiliation: '7 Head',
    gender: 'female',
  },
  {
    firstName: 'Priscilla',
    lastName: 'Timpson',
    email: 'priscillamwayman@gmail.com',
    phone: '435-467-3844',
    affiliation: '2 Head',
    gender: 'female',
  },
  {
    firstName: 'Rachel',
    lastName: 'Dockstader',
    email: 'rachelt_2008@hotmail.com',
    phone: '435-212-0718',
    affiliation: '10 Head',
    gender: 'female',
  },
  {
    firstName: 'Rebecca',
    lastName: 'Barlow',
    email: 'rose_1309@hotmail.com',
    phone: '435-619-4826',
    affiliation: 8,
    gender: 'female',
  },
  {
    firstName: 'Rebecca D.',
    lastName: 'Timpson',
    email: 'lily_vohn@hotmail.com',
    phone: '435-212-0116',
    affiliation: 6,
    gender: 'female',
  },
  {
    firstName: 'Rebecca F.',
    lastName: 'Timpson',
    email: 'rfischer@primeres.com',
    phone: '435-212-0160',
    affiliation: 5,
    gender: 'female',
  },
  {
    first: 'Charles',
    last: 'Timpson',
    email: 'ctimpson@exceldesign.us',
    phone: 4357058758,
    skills: 'Dairy Products',
  },
  {
    firstName: 'Rhoda',
    lastName: 'Dockstader',
    email: 'NA',
    phone: '928-875-2128',
    affiliation: 1,
    gender: 'female',
  },
  {
    firstName: 'Rose',
    lastName: 'Cawley',
    email: 'rosetcawley@yahoo.com',
    phone: 4352120548,
    affiliation: 8,
    gender: 'female',
  },
  {
    firstName: 'Ruth',
    lastName: 'Hammon',
    email: 'ruthietimpson@hotmail.com',
    phone: '435-467-9268',
    affiliation: 10,
    gender: 'female',
  },
  {
    first: 'Ryan',
    last: 'Hammon',
    email: 'ryan.hammon@encompass-az.org',
    phone: 4352123498,
    skills: '',
  },
  {
    first: 'Brian',
    last: 'Timpson',
    email: 'brian.a.timpson@gmail.com',
    phone: 4352123072,
    skills: '',
  },
  {
    firstName: 'Sarah B',
    lastName: 'Hammon',
    email: 'sarahhammon@ymail.com',
    phone: '435-467-9265',
    affiliation: 4,
    gender: 'female',
  },
  {
    first: 'Aaron',
    last: 'Dockstader',
    email: 'atd.dhi@gmail.com',
    phone: 4354672696,
    skills: 'Construction',
  },
  {
    firstName: 'Sophia',
    lastName: 'Zitting',
    email: 'sophiazitting@gmail.com',
    phone: '435-817-0424',
    affiliation: 8,
    gender: 'female',
  },
  {
    first: 'Robert W.',
    last: 'Timpson',
    email: 'rwt1818@hotmail.com',
    phone: 4352120155,
    skills: 'Livestock, Construction',
  },
  {
    first: 'Hyrum',
    last: 'Timpson',
    email: 'ht284857@plusonecompany.info',
    phone: 4356197868,
    skills: 'Chicken Enterprise',
  },
  {
    first: 'Enoch',
    last: 'Wayman',
    email: '',
    phone: 8019069030,
    skills: '',
  },
  {
    first: 'Lorin',
    last: 'Timpson',
    email: 'lbtimpson@hotmail.com',
    phone: 4356808141,
    skills: 'Construction',
  },
  {
    first: 'David',
    last: 'Timpson',
    email: 'ddt@cpaz.net',
    phone: 4354678779,
    skills: 'President and Planning Committe Head',
  },
  {
    first: 'Matthew',
    last: 'Zitting',
    email: 'mhzitting@gmail.com',
    phone: 8019033204,
    skills: '',
  },
  {
    first: 'Ammon',
    last: 'Timpson',
    email: 'ammontimpson@gmail.com',
    phone: 4356168131,
    skills: '',
  },
  {
    first: 'John C.',
    last: 'Knudson',
    email: 'jcyrusk@hotmail.com',
    phone: 4354678106,
    skills: 'Business Planning',
  },
  {
    first: 'Jared A',
    last: 'Knudson',
    email: 'Jared.knudson19@gmail.com',
    phone: 4352123329,
    skills: '',
  },
  {
    firstName: 'Zina',
    lastName: 'Blackmore',
    email: 'zina.blackmore@imail.org',
    phone: '435-669-8984',
    affiliation: 5,
    gender: 'female',
  },
  {
    first: 'Patrick',
    last: 'Dockstader',
    email: 'Borderstore2@gmail.com',
    phone: 4352120576,
    skills: '',
  },
  {
    first: 'Theral III',
    last: 'Dockstader',
    email: 'theral84@gmail.com',
    phone: 4354672128,
    skills: '',
  },
  {
    first: 'Levi G.',
    last: 'Hammon',
    email: 'levihammon@outlook.com',
    phone: 4356168452,
    skills: 'Pigs/ Construction',
  },
  {
    firstName: 'Katelynn D',
    lastName: 'Zitting',
    email: '',
    phone: '435-619-7624',
    affiliation: 9,
    gender: 'female',
  },
  {
    firstName: 'Sarah',
    lastName: 'Cawley',
    email: '',
    phone: '435-212-1974',
    affiliation: 9,
    gender: 'female',
  },
  {
    first: 'Nathan',
    last: 'Burnham',
    email: 'nathanwburnham@hotmail.com',
    phone: 4352120307,
    skills: 'Livestock, Construction',
  },
  {
    first: 'Kris',
    last: 'Holm',
    email: 'kholm71@yahoo.com',
    phone: 7022773945,
    skills: '',
  },
  {
    first: 'James',
    last: 'Timpson',
    email: 'jamesatimpson@hotmail.com',
    phone: 4356914287,
    skills: 'Sales Enterprise',
  },
  {
    firstName: 'Katrina D',
    lastName: 'Hammon',
    email: '',
    phone: '435-467-8995',
    affiliation: 10,
    gender: 'female',
  },
  {
    first: 'William',
    last: 'Wayman',
    email: 'william.wayman@yahoo.com',
    phone: 8018314350,
    skills: '',
  },
  {
    firstName: 'Devan B',
    lastName: 'Zitting',
    email: '',
    phone: '435.212.0414',
    affiliation: 10,
    gender: 'female',
  },
  {
    first: 'Kevin Jr.',
    last: 'LeBaron',
    email: 'kevaleb@gmail.com',
    phone: 4352123705,
    skills: 'Tech',
  },
  {
    firstName: 'Carole',
    lastName: 'Zitting',
    email: 'cwzitting@gmail.com',
    phone: '435-616-2223',
    affiliation: 2,
    gender: 'female',
  },
  {
    first: 'Justin',
    last: 'Hammon',
    email: 'juxx@hotmail.com',
    phone: 4356914380,
    skills: '',
  },
  {
    firstName: 'Alec',
    lastName: 'Dockstader',
    email: '',
    phone: 4352120371,
    affiliation: '',
    gender: 'male',
  },
  {
    first: 'Allen',
    last: 'Zitting',
    email: 'alzitting@villagecapital.com',
    phone: 4352293461,
    affiliation: '',
    gender: 'male',
  },
  {
    firstName: 'Allen A.',
    lastName: 'Timpson',
    email: 'atimpson@hotmail.com',
    phone: 4352120584,
    affiliation: '',
    gender: 'male',
  },
  {
    firstName: 'Allen K.',
    lastName: 'Zitting',
    email: 'allen@amlc.net',
    phone: 4357050955,
    affiliation: 'Solar Manager, Financial Committee, Farm Manager',
    gender: 'male',
  },
  {
    first: 'Allen A.',
    last: 'Timpson',
    email: 'atimpson@hotmail.com',
    phone: 4352120584,
    skills: '',
  },
  {
    first: 'Allen K.',
    last: 'Zitting',
    email: 'allen@amlc.net',
    phone: 4357050955,
    skills: 'Solar Manager, Financial Committee, Farm Manager',
  },
  {
    first: 'Alma A.',
    last: 'Hammon',
    email: 'almahammon@cpaz.net',
    phone: 4354673544,
    affiliation: '',
    gender: 'male',
  },
  {
    first: 'Alma I.',
    last: 'Hammon',
    email: 'aih1975@hotmail.com',
    phone: 4356914376,
    affiliation: 'Beef',
    gender: 'male',
  },
  {
    firstName: 'Ammon',
    lastName: 'Timpson',
    email: 'ammontimpson@gmail.com',
    phone: 4356168131,
    affiliation: '',
    gender: 'male',
  },
  {
    first: 'Andy',
    last: 'Cook',
    email: 'cooksco@outlook.com',
    phone: 8012440719,
    affiliation: '',
    gender: 'male',
  },
  {
    first: 'Ariel',
    last: 'Hammon',
    email: 'arielhammon@gmail.com',
    phone: 4356915230,
    affiliation: 'Planning Committee',
    gender: 'male',
  },
  {
    first: 'Benjamin',
    last: 'Dockstader',
    email: 'ben_dock@hotmail.com',
    phone: 4352128009,
    affiliation: '',
    gender: 'male',
  },
  {
    firstName: 'Brian',
    lastName: 'Timpson',
    email: 'brian.a.timpson@gmail.com',
    phone: 4352123072,
    affiliation: '',
    gender: 'male',
  },
  {
    first: 'Brigham',
    last: 'Timpson',
    email: 'brigtimpson@gmail.com',
    phone: 4356801472,
    affiliation: '',
    gender: 'male',
  },
  {
    first: 'Charles',
    last: 'Bradshaw',
    email: 'chuckybill68@gmail.com',
    phone: 4356695816,
    affiliation: 'Dairy Manager',
    firstName: 'Charles',
    lastName: 'Timpson',
    email: 'ctimpson@exceldesign.us',
    phone: 4357058758,
    affiliation: 'Dairy Products',
    gender: 'male',
  },
  {
    first: 'Dan H.',
    email: 'danhammon@cpaz.net',
    phone: 4354675905,
    affiliation: '',
    gender: 'male',
  },
  {
    firstName: 'David',
    lastName: 'Timpson',
    email: 'ddt@cpaz.net',
    phone: 4354678779,
    affiliation: 'President and Planning Committe Head',
    gender: 'male',
  },
  {
    first: 'David Jr.',
    last: 'Dockstader',
    email: 'tdavedock@hotmail.com',
    phone: 4356802128,
    affiliation: 'Construction',
    gender: 'male',
  },
  {
    first: 'David V Jr.',
    last: 'Berg',
    email: 'davidberg26@gmail.com',
    phone: 4352120069,
    affiliation: 'Maintenance',
    gender: 'male',
  },
  {
    first: 'Don',
    last: 'Timpson',
    email: 'timpsond@yahoo.com',
    phone: 4354672466,
    affiliation: 'Financial Committee',
    gender: 'male',
  },
  {
    first: 'Dustin',
    last: 'Hammon',
    email: 'dham28.dh@gmail.com',
    phone: 4357053920,
    affiliation: '',
    gender: 'male',
  },
  {
    firstName: 'Enoch',
    lastName: 'Wayman',
    email: '',
    phone: 8019069030,
    affiliation: '',
    gender: 'male',
  },
  {
    firstName: 'Ephraim',
    lastName: 'Hammon',
    email: 'ephraim_hammon@yahoo.com',
    phone: 4356165687,
    affiliation: '2nd Counselor',
    gender: 'male',
  },
  {
    firstName: 'Gordon Jr',
    lastName: 'Zitting',
    email: 'gordon13zitting@gmail.com',
    phone: 4352120656,
    affiliation: '',
    gender: 'male',
  },
  {
    first: 'Gordon K.',
    last: 'Zitting',
    email: 'gordkz@gmail.com',
    phone: 4356804974,
    affiliation: '',
    gender: 'male',
  },
  {
    first: 'Gregory',
    last: 'Kelsch',
    email: 'gregory@fashioncabinet.com',
    phone: 4355748514,
    affiliation: '',
    gender: 'male',
  },
  {
    first: 'Haven B.',
    last: 'Barlow',
    email: 'hbbarlow67@gmail.com',
    phone: 4356914795,
    affiliation: '',
    gender: 'male',
  },
  {
    first: 'Haven R. (Sr)',
    last: 'Barlow',
    email: 'havenrbarlow@gmail.com',
    phone: 4356911068,
    affiliation: '',
    gender: 'male',
  },
  {
    first: 'Heber',
    last: 'Hammon',
    email: '',
    phone: 4356914795,
    affiliation: '',
    gender: 'male',
  },
  {
    firstName: 'Hyrum',
    lastName: 'Timpson',
    email: 'ht284857@plusonecompany.info',
    phone: 4356197868,
    affiliation: 'Chicken Enterprise',
    gender: 'male',
  },
  {
    first: 'Isaac',
    last: 'Barlow',
    email: 'isaac@busybusy.com',
    phone: 4356913520,
    affiliation: 'Financial, Tech',
    gender: 'male',
  },
  {
    first: 'Isaiah',
    last: 'Barlow',
    email: 'zaylow@gmail.com',
    phone: 4352188028,
    affiliation: '',
    gender: 'male',
  },
  {
    first: 'Jacob',
    last: 'Hammon',
    email: 'bigjmh78@gmail.com',
    phone: 4352120080,
    affiliation: 'Livestock',
    gender: 'male',
  },
  {
    first: 'Jacob',
    last: 'Cawley',
    email: 'jhcawley@hotmail.com',
    phone: 4354678292,
    affiliation: '',
    gender: 'male',
  },
  {
    first: 'Jared D.',
    last: 'Zitting',
    email: '',
    phone: 4357038221,
    affiliation: '',
    gender: 'male',
  },
  {
    first: 'Jason',
    last: 'Hammon',
    email: 'jasonhammon@hotmail.com',
    phone: 4352120110,
    affiliation: 'Pig Committee',
    gender: 'male',
  },
  {
    first: 'John',
    last: 'Blackmore',
    email: 'zina@cpaz.net',
    phone: 4356698571,
    affiliation: 'Feed',
    gender: 'male',
  },
  {
    first: 'John',
    last: 'Cawley',
    email: 'Cawleyjt@hotmail',
    phone: 4354677128,
    affiliation: '',
    gender: 'male',
  },
  {
    first: 'John',
    last: 'Cook',
    email: 'noelfrieda@cpaz.net',
    phone: 4352128053,
    affiliation: 'Maintenance',
    gender: 'male',
  },
  {
    first: 'John W.',
    last: 'Timpson',
    email: 'jtimpson45@gmail.com',
    phone: 4356914808,
    affiliation: 'Financial Chair',
    gender: 'male',
  },
  {
    first: 'Joseph',
    last: 'Musser',
    email: 'largo98@yahoo.com',
    phone: 4354675289,
    affiliation: '',
    gender: 'male',
  },
  {
    first: 'Joseph',
    last: 'Timpson',
    email: 'Joseph@amlc.net',
    phone: 4352120618,
    affiliation: '',
    gender: 'male',
  },
  {
    first: 'Joseph Jr.',
    last: 'Hammon',
    email: 'josephhammon@hotmail.com',
    phone: 4358791251,
    affiliation: '',
    gender: 'male',
  },
  {
    firstName: 'Joshua',
    lastName: 'Hammon',
    email: 'josh@cpaz.net',
    phone: 4354670581,
    affiliation: '',
    gender: 'male',
  },
  {
    first: 'Joshua',
    last: 'Timpson',
    email: 'ashtar88@hotmail.com',
    phone: 4352120695,
    affiliation: '',
    gender: 'male',
  },
  {
    first: 'Lars',
    last: 'Dutson',
    email: 'bigled72@hotmail.com',
    phone: 9282181443,
    affiliation: '',
    gender: 'male',
  },
  {
    firstName: 'Levi G.',
    lastName: 'Hammon',
    email: 'levihammon@outlook.com',
    phone: 4356168452,
    affiliation: 'Pigs/ Construction',
    gender: 'male',
  },
  {
    first: 'Lorin',
    last: 'Hammon',
    email: 'lfh@cpaz.net',
    phone: 4354678251,
    affiliation: 'Manager of Pigs',
    gender: 'male',
  },
  {
    first: 'Lorin C.',
    last: 'Zitting',
    email: '',
    phone: 4354672230,
    affiliation: '',
    gender: 'male',
  },
  {
    first: 'Lorin C. Jr.',
    last: 'Zitting',
    email: 'lorin@assetinsurancellc.com',
    phone: 4356913001,
    affiliation: 'Purchasing Enterprise',
    gender: 'male',
  },
  {
    first: 'Michael',
    last: 'Cawley',
    email: 'MBCawley_3@yahoo.com',
    phone: 4352123270,
    affiliation: 'Education, Masonry, Labor Database',
    gender: 'male',
  },
  {
    firstName: 'Nathan',
    lastName: 'Burnham',
    email: 'nathanwburnham@hotmail.com',
    phone: 4352120307,
    affiliation: 'Livestock, Construction',
    gender: 'male',
  },
  {
    first: 'Nathan',
    last: 'Zitting',
    email: 'natez87@hotmail.com',
    phone: 4356693514,
    affiliation: '',
    gender: 'male',
  },
  {
    first: 'Richard M.',
    last: 'Timpson',
    email: 'richard@cpaz.net',
    phone: 4354678220,
    affiliation: '1st Counselor, Retail',
    gender: 'male',
  },
  {
    firstName: 'Robert W.',
    lastName: 'Timpson',
    email: 'rwt1818@hotmail.com',
    phone: 4352120155,
    affiliation: 'Livestock, Construction',
    gender: 'male',
  },
  {
    first: 'Roger C.',
    last: 'Knudson',
    email: 'rck1967@hotmail.com',
    phone: 4352123328,
    affiliation: 'Finance Committee, Accounting Manager',
  },
  {
    first: 'Rueben',
    email: 'rhcawley@yahoo.com',
    phone: 7028823363,
    skills: 'Compliance Committee Head',
    affiliation: 'Compliance Committee Head',
    gender: 'male',
  },
  {
    first: 'Samuel',
    last: 'Timpson',
    email: 'samueltimpson@primeres.com',
    phone: 4352123048,
    skills: 'Butcher',
    affiliation: 'Butcher',
    gender: 'male',
  },
  {
    firstName: 'Theral III',
    lastName: 'Dockstader',
    email: 'theral84@gmail.com',
    phone: 4354672128,
    affiliation: '',
    gender: 'male',
  },
  {
    firstName: 'Theral R.',
    lastName: 'Timpson',
    email: 'theral@cpaz.net',
    phone: 4352128200,
    affiliation: 'Chicken Enterprise',
    gender: 'male',
  },
  {
    first: 'Thomas',
    last: 'Hammon',
    email: '',
    phone: 8015149791,
    skills: '',
    affiliation: '',
    gender: 'male',
  },
  {
    firstName: 'Warren',
    lastName: 'Hammon',
    email: 'warrenhammon@yahoo.com',
    phone: 4354679263,
    affiliation: 'Honey Steward, Pig Assistant',
    gender: 'male',
  },
  {
    firstName: 'William',
    lastName: 'Wayman',
    email: 'william.wayman@yahoo.com',
    phone: 8018314350,
    affiliation: '',
    gender: 'male',
  },
  {
    firstName: 'Matthew',
    lastName: 'Zitting',
    email: 'mhzitting@gmail.com',
    phone: 8019033204,
    affiliation: '',
    gender: 'male',
  },
  {
    first: 'Nephi',
    last: 'Hammon',
    email: 'nephihammon@hotmail.com',
    phone: 4354671138,
    skills: '',
  },
];
